server:
  port: 9091

spring:
  config:
    import: ./secrets.properties
  application:
    name: order-microservice
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_CONNECTION_URL}/${POSTGRES_DATABASE_NAME}
    username: ${POSTGRES_DATABASE_USERNAME}
    password: ${POSTGRES_DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    open-in-view: false
